In [4]:
import numpy as np

In [5]:
n = 10
 
pascal = np.zeros((n,n), dtype=int)
pascal[0,0] = pascal[1,0] = pascal[1,1] = 1

for row in range(2,n):
    for col in range(0,row+1):
        pascal[row,col] = pascal[row-1,col-1] + pascal[row-1,col]
print(pascal)

[[  1   0   0   0   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   0   0   0]
 [  1   2   1   0   0   0   0   0   0   0]
 [  1   3   3   1   0   0   0   0   0   0]
 [  1   4   6   4   1   0   0   0   0   0]
 [  1   5  10  10   5   1   0   0   0   0]
 [  1   6  15  20  15   6   1   0   0   0]
 [  1   7  21  35  35  21   7   1   0   0]
 [  1   8  28  56  70  56  28   8   1   0]
 [  1   9  36  84 126 126  84  36   9   1]]
